title:              ShahdMoussa
email:              shahdmoussa18@gmail.com
description:        Cyber Security Blog
author:             ShahdMoussa
baseurl:            "/"
url:                "https://shahddmoussa.github.io"

# Social Profiles
github_username:   shahddmoussa
linkedin_username: shahdmoussa

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
